# -*- coding: utf-8 -*-
"""Day-4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_sHcDpJC2-70Nu66sNZ_hQV-iGimaZGN
"""

#operator
#1. assignment operator
a=200
#= a + 100
a += 100
print(a)

#comparison operation

a = 100
b = 200

print(a<b)
print(a>b)
print(a!=b)

# logical operator
print(True and True)
print(True and False)


print(True or True)
print(True or False)

print(not(True))#which change

print(1> 2 and 2>1)

s="subhash"
s2="subhash r"
print(("s" in s ) and  ("a" in s2))

num1=int(input("enter the first no.: "))
num2=int(input("Enter the second no.: "))

if(num1 > 10 and num2> 10):
  print("both are grater than 10")

if(num1 < 5 or num2 < 5):
  print(" atleast one number is less than 5")

if(not(num1> num2)):
  print("num1 is not grater than num2")

