# -*- coding: utf-8 -*-
"""Day-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15QIIBdY4EHnqrqFH3Kvz_D30makMT5e6
"""

from types import GeneratorType
#tupples and sets
#order immutable
#once we create, we can't change it
# we use ()

print("hello")
gender = ("male", "female", "others","male",(1,2,3,))
print(gender)
print(type(gender))
print(len(gender))

print(gender[1])

# it give erroe : gender [0]= "sigma male"
print("male" in gender) # membership

print(gender.index("male"))

# sets
# collection of uniqe items
# unorder, unindex
# we use the {}

s={1,233,3}
print(s) # stes are unorder

# give an error : print(s[0])   ..'set' object is not subscriptable

print(type(s))

s2 ={}

s2=set((1,2,3))
print(type(s2))

print("...")
s3={}
print(type(s3))

s3=set()
print(type(s3))

s1 = {1,2,3,4}
s2 ={4,5,6,}

print(s1 | s2) # union
print(s1 & s2) #intersection
print(s1 - s2) # difference

s={1,2,3,4,5,6}
s.add(4)
print(s)
# s.remove(22)     #if the value is in the set we can use this
s.discard(323)

s.pop()
print(s)

print(s.clear()) # remove all the elements

'''Tuple Operations:

Create a tuple with 5 elements.
Try to modify one of the elements. What happens?
Perform slicing on the tuple to extract the second and third elements.
Concatenate the tuple with another tuple.'''

t1=(1,2,3,4,5)

 #t[0]= 2 #  'tuple' object does not support item assignment

print(t1)

print(t1[1:3])

t2=(6,7,8,9)
print(t1 + t2)

list=[1,2,3,4]

t= tuple(list)
print(t)
# t.add(55)      # tupple is immutable
print(set(t))

