# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfIUhFCLp07YnjsbrOKIozBVjODmcgtb
"""

#string method
a="message  "

print(a.upper())
print(a.lower())
print(a.strip()*2)

print(a.replace("message","hello"))

name='''hello "deepak" what are you doing'''
print(name)
#lenght of the string
print(len(name))


#accesing the string elements
name='subhash'
print(name[0])
print(name[2: 5])
print(name[2:])

print(name[-1])

#start:end:step

print(name[::2])

print("hello \n hi\t heee \\ hii")

