# -*- coding: utf-8 -*-
"""Day-7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MkWHnXJVULaGcaKRAPOZrlTwctDgwnvC
"""

# Dictionaries
# collection key-value pair
# unorder
# mutable
# use {}
meaning ={"bat":"use to hit",
          "ball": "this is hit"
          }
print(meaning["bat"]) # to acces we use the key
print(meaning.get("wicket", "not found")) # safe accesing

print(meaning)
meaning["virat"]= "duck"
print(meaning)

#update

print("updating...")
meaning["virat"]= "GOAT"
print(meaning)

# removing

x = meaning.pop("bat")
print(meaning)

del meaning['ball']
print(meaning)

meaning ={"bat":"use to hit",
          "ball": "this is hit"
          }

print(meaning.keys())
print(meaning.values())

student={"ram": "boy",
         "sita": "girl"
         }

# addinng 2 dict
meaning.update(student)

print(meaning)

item1 ={
    "name": "milk",
    "weight": 1,
    "Price": 67
}

item2={
    'name':'sugar',
    'weight':1,
    'price' : 66
}

items = [item1,item2,]
print(items)

print(f"Total weight : { item1["weight"]+ item2["weight"]}")

'''Create a dictionary to store information about 5 cities in Karnataka and their famous dishes.
1.Add a new city and its dish to the dictionary.
2.Update the dish for Bengaluru.
3.Remove one city from the dictionary.
4.Use the keys() method to print all city names in the dictionary.
5.Use the values() method to print all dishes in the dictionary.
'''

dish ={
    "Mysuru": "Mysure pak",
    "mangaluru": "Neer dosa",
    "Bengaluru": "bisi bele bath"
}
# 4.

print(dish.keys())

print("----------------------------")

print(dish.values())

# 5.
print("----------------------------")

dish["Mandya"] = "sugarcane juice"
print(dish)



#updating

dish["Bengaluru"] = "rice and samber"
print(dish)


#deleting

x = dish.pop("mangaluru")
print(f"deleted item is : ", x)

del dish["Mysuru"]
print(dish)

