# -*- coding: utf-8 -*-
"""Day-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/155904cOHqWZpgZqUik8PofXuKMJLRP11
"""

#list in python
#list is a ordered, mutable, and allow the duplicate elements
#it can holds the differnet of data types
items = ["car", " bike", "flower"]

print(items)
print(items[1])

list = [22, 'os', 'dbms', 0.22]
print(list)
print(list[0])

items = ["car", " bike", "flower"]

print(items)
items.pop() # remove the last element
items.pop(0)#by adding the index we can delet


items.append('bru')# is appends at last position
items.append('tea')


items.insert(1,"fruits")

items.remove("bru")

items[0]="bmw"
print(items)

items.clear()# it will clear the list

l =[1020,20,300,1100]
l[0::2]

print(len(l))
sort = sorted(l)

print(sort)
print(sum(l))
print(l.count(300)) # it counts the no. of time that element appearance

m=[[1,2],[3,4]]
print(m[0])
print(m[0][1])

print(m) #nesting

'''List Manipulation Exercise:

Create a list of 5 items (strings or numbers).
Add a new item to the end of the list and another at the second position.
Remove the third item from the list.
Print the list after each operation.
'''

list =[1,2,3,4,5,6]

list.append(7)
print(list)

list.insert(1,22)
print(list)

list.remove(2)
print(list)

list=[10,32,42,1,53]

sort= sorted(list)
list.sort(reverse= True)
print("desending order: ", list)

#reverse the sorted list
list.reverse()
print("reversed list: ", list)

