# -*- coding: utf-8 -*-
"""Day-2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYr1OYjy-J0R6CqhgY-zysValBZ98GMx
"""

print("hello")

age=input("Age: ")
print(age)

boy_name= input("boy name :  ")
girl_name = input("girl name: ")

b_age=int(input("age: "))
g_name=int(input("age: "))

# using abs becouse sometime boy might be younger
age_diff= abs(b_age - g_name)

'''this
is multiline
comments
'''
print( boy_name +" is a friend of "+ girl_name +" and their age difference is ", str(age_diff) )

